package com.reactordevelopment.ImperiumLite;

import android.content.Context;
import android.graphics.Color;

import java.util.ArrayList;

public class Classic extends Map {
public static final int MAP_DRAWABLE = R.drawable.classic;
    public Classic(Context context){
        provinceList = new Province[44];
        id = 0;
        continents = new Continent[6];
        imperiumMap = 0;
        overScale = 1.35;
		statusScale = 2;
        mapFilePath = "classicMap/";
        assemble(context);
    }
    public void assemble(Context context){
        double scaleX = 1;
        double scaleY = 1;
        double shiftX = 0;
        double shiftY = 0;
        int color;
        borders = new ArrayList<>();
	    color = Color.argb(255, 110, 181, 74);

        continents[0] = new Continent(0, color, "North America", 0, 0.5+vary());
	    borders.add(0, 34);     borders.add(1, 2);     borders.add(2, 4); 
	    provinceList[0] = new Province(context, 1, 0, bordering(), (int)(scaleX*60+shiftX), (int)(scaleY*96+shiftY), "Alaska", 0.9+vary());
	    borders = new ArrayList<>();
	    borders.add(0, 1);     borders.add(1, 4);     borders.add(2, 5);     borders.add(3, 3); 
	    provinceList[1] = new Province(context, 2, 0, bordering(), (int)(scaleX*131+shiftX), (int)(scaleY*103+shiftY), "NorthWest Territory", 0.5+vary());
	    borders = new ArrayList<>();
	    borders.add(0, 2);     borders.add(1, 1);     borders.add(2, 5);     borders.add(3, 7); 
	    provinceList[3] = new Province(context, 4, 0, bordering(), (int)(scaleX*144+shiftX), (int)(scaleY*136+shiftY), "Alberta", 0.5+vary());
	    borders = new ArrayList<>();
	    borders.add(0, 4);     borders.add(1, 7);     borders.add(2, 8);     borders.add(3, 3);     borders.add(4, 2);     borders.add(5, 6); 
	    provinceList[4] = new Province(context, 5, 0, bordering(), (int)(scaleX*219+shiftX), (int)(scaleY*138+shiftY), "Ontario", 0.5+vary());
	    borders = new ArrayList<>();
	    borders.add(0, 4);     borders.add(1, 5);     borders.add(2, 8);     borders.add(3, 9); 
	    provinceList[6] = new Province(context, 7, 0, bordering(), (int)(scaleX*153+shiftX), (int)(scaleY*166+shiftY), "Western United States", 0.5+vary());
	    borders = new ArrayList<>();
	    borders.add(0, 9);     borders.add(1, 8);     borders.add(2, 5);     borders.add(3, 6);     borders.add(4, 7); 
	    provinceList[7] = new Province(context, 8, 0, bordering(), (int)(scaleX*203+shiftX), (int)(scaleY*167+shiftY), "Eastern United States", 0.5+vary());
	    borders = new ArrayList<>();
	    borders.add(0, 8);     borders.add(1, 5);     borders.add(2, 3); 
	    provinceList[5] = new Province(context, 6, 0, bordering(), (int)(scaleX*272+shiftX), (int)(scaleY*132+shiftY), "Quebec", 0.5+vary());
	    borders = new ArrayList<>();
	    borders.add(0, 8);     borders.add(1, 9);     borders.add(2, 10);     borders.add(3, 7); 
	    provinceList[8] = new Province(context, 9, 0, bordering(), (int)(scaleX*168+shiftX), (int)(scaleY*205+shiftY), "Mexico", 0.6+vary());
	    borders = new ArrayList<>();
	    borders.add(0, 14);     borders.add(1, 5);     borders.add(2, 2);     borders.add(3, 6); 
	    provinceList[2] = new Province(context, 3, 0, bordering(), (int)(scaleX*287+shiftX), (int)(scaleY*53+shiftY), "Greenland", 0.8+vary());
	    borders = new ArrayList<>();
	    continents[0].fill(0, 8);
	    color = Color.argb(255, 255, 134, 128);

        continents[1] = new Continent(1, color, "South America", 2, 0.7+vary());
	    borders.add(0, 10);     borders.add(1, 11);     borders.add(2, 12);     borders.add(3, 9); 
	    provinceList[9] = new Province(context, 10, 1, bordering(), (int)(scaleX*201+shiftX), (int)(scaleY*250+shiftY), "Venezuela", 0.7+vary());
	    borders = new ArrayList<>();
	    borders.add(0, 13);     borders.add(1, 12);     borders.add(2, 11);     borders.add(3, 21);     borders.add(4, 10); 
	    provinceList[11] = new Province(context, 12, 1, bordering(), (int)(scaleX*217+shiftX), (int)(scaleY*270+shiftY), "Brazil", 0.8+vary());
	    borders = new ArrayList<>();
	    borders.add(0, 11);     borders.add(1, 12);     borders.add(2, 13);     borders.add(3, 10); 
	    provinceList[10] = new Province(context, 11, 1, bordering(), (int)(scaleX*196+shiftX), (int)(scaleY*280+shiftY), "Peru", 0.5+vary());
	    borders = new ArrayList<>();
	    borders.add(0, 13);     borders.add(1, 11);     borders.add(2, 12); 
	    provinceList[12] = new Province(context, 13, 1, bordering(), (int)(scaleX*231+shiftX), (int)(scaleY*328+shiftY), "Argentina", 0.5+vary());
	    borders = new ArrayList<>();
	    continents[1].fill(9, 12);
	    color = Color.argb(255, 102, 102, 232);

        continents[2] = new Continent(2, color, "Europe", 5, 0.2+vary());
	    borders.add(0, 3);     borders.add(1, 18);     borders.add(2, 15); 
	    provinceList[13] = new Province(context, 14, 2, bordering(), (int)(scaleX*380+shiftX), (int)(scaleY*126+shiftY), "Iceland", 0.7+vary());
	    borders = new ArrayList<>();
	    borders.add(0, 15);     borders.add(1, 18);     borders.add(2, 17);     borders.add(3, 16);     borders.add(4, 14); 
	    provinceList[14] = new Province(context, 15, 2, bordering(), (int)(scaleX*373+shiftX), (int)(scaleY*150+shiftY), "Great Britain", 0.5+vary());
	    borders = new ArrayList<>();
	    borders.add(0, 17);     borders.add(1, 19);     borders.add(2, 16);     borders.add(3, 20);     borders.add(4, 18);     borders.add(5, 15); 
	    provinceList[16] = new Province(context, 17, 2, bordering(), (int)(scaleX*412+shiftX), (int)(scaleY*159+shiftY), "Northern Europe", 0.5+vary());
	    borders = new ArrayList<>();
	    borders.add(0, 17);     borders.add(1, 20);     borders.add(2, 27);     borders.add(3, 22);     borders.add(4, 21);     borders.add(5, 16); 
	    provinceList[18] = new Province(context, 19, 2, bordering(), (int)(scaleX*418+shiftX), (int)(scaleY*182+shiftY), "Southern Europe", 0.8+vary());
	    borders = new ArrayList<>();
	    borders.add(0, 16);     borders.add(1, 21);     borders.add(2, 19);     borders.add(3, 17);     borders.add(4, 15); 
	    provinceList[15] = new Province(context, 16, 2, bordering(), (int)(scaleX*374+shiftX), (int)(scaleY*181+shiftY), "Western Europe", 0.6+vary());
	    borders = new ArrayList<>();
	    borders.add(0, 14);     borders.add(1, 15);     borders.add(2, 17);     borders.add(3, 20); 
	    provinceList[17] = new Province(context, 18, 2, bordering(), (int)(scaleX*414+shiftX), (int)(scaleY*71+shiftY), "Scandinavia", 0.5+vary());
	    borders = new ArrayList<>();
	    borders.add(0, 27);     borders.add(1, 28);     borders.add(2, 29);     borders.add(3, 19);     borders.add(4, 17);     borders.add(5, 18); 
	    provinceList[19] = new Province(context, 20, 2, bordering(), (int)(scaleX*453+shiftX), (int)(scaleY*82+shiftY), "Ukraine", 0.5+vary());
	    borders = new ArrayList<>();
	    continents[2].fill(13, 19);
	    color = Color.argb(255, 255, 223, 128);

        continents[3] = new Continent(3, color, "Africa", 3, 0.5+vary());
	    borders.add(0, 22);     borders.add(1, 24);     borders.add(2, 27);     borders.add(3, 20);     borders.add(4, 21);     borders.add(5, 19); 
	    provinceList[21] = new Province(context, 22, 3, bordering(), (int)(scaleX*420+shiftX), (int)(scaleY*229+shiftY), "Egypt", 0.7+vary());
	    borders = new ArrayList<>();
	    borders.add(0, 22);     borders.add(1, 23);     borders.add(2, 12);     borders.add(3, 16);     borders.add(4, 19);     borders.add(5, 24); 
	    provinceList[20] = new Province(context, 21, 3, bordering(), (int)(scaleX*351+shiftX), (int)(scaleY*222+shiftY), "North Africa", 0.6+vary());
	    borders = new ArrayList<>();
	    borders.add(0, 23);     borders.add(1, 24);     borders.add(2, 26);     borders.add(3, 27);     borders.add(4, 22);     borders.add(5, 21); 
	    provinceList[23] = new Province(context, 24, 3, bordering(), (int)(scaleX*453+shiftX), (int)(scaleY*265+shiftY), "East Africa", 0.8+vary());
	    borders = new ArrayList<>();
	    borders.add(0, 25);     borders.add(1, 26);     borders.add(2, 24); 
	    provinceList[25] = new Province(context, 26, 3, bordering(), (int)(scaleX*499+shiftX), (int)(scaleY*352+shiftY), "Madagascar", 0.5+vary());
	    borders = new ArrayList<>();
	    borders.add(0, 25);     borders.add(1, 24);     borders.add(2, 21); 
	    provinceList[22] = new Province(context, 23, 3, bordering(), (int)(scaleX*414+shiftX), (int)(scaleY*296+shiftY), "Congo", 0.5+vary());
	    borders = new ArrayList<>();
	    borders.add(0, 24);     borders.add(1, 26);     borders.add(2, 25);     borders.add(3, 23); 
	    provinceList[24] = new Province(context, 25, 3, bordering(), (int)(scaleX*422+shiftX), (int)(scaleY*339+shiftY), "South Africa", 0.5+vary());
	    borders = new ArrayList<>();
	    continents[3].fill(20, 25);
	    color = Color.argb(255, 152, 232, 102);

        continents[4] = new Continent(4, color, "Asia", 7, 0.2+vary());
	    borders.add(0, 30);     borders.add(1, 36);     borders.add(2, 29);     borders.add(3, 28);     borders.add(4, 20); 
	    provinceList[28] = new Province(context, 29, 4, bordering(), (int)(scaleX*560+shiftX), (int)(scaleY*100+shiftY), "Ural", 0.8+vary());
	    borders = new ArrayList<>();
	    borders.add(0, 29);     borders.add(1, 36);     borders.add(2, 37);     borders.add(3, 28);     borders.add(4, 27);     borders.add(5, 20); 
	    provinceList[27] = new Province(context, 28, 4, bordering(), (int)(scaleX*522+shiftX), (int)(scaleY*161+shiftY), "Afganistan", 0.7+vary());
	    borders = new ArrayList<>();
	    borders.add(0, 20);     borders.add(1, 28);     borders.add(2, 37);     borders.add(3, 22);     borders.add(4, 24);     borders.add(5, 19); 
	    provinceList[26] = new Province(context, 27, 4, bordering(), (int)(scaleX*470+shiftX), (int)(scaleY*205+shiftY), "Middle East", 0.6+vary());
	    borders = new ArrayList<>();
	    borders.add(0, 38);     borders.add(1, 37);     borders.add(2, 29);     borders.add(3, 30);     borders.add(4, 33);     borders.add(5, 39);     borders.add(6, 28); 
	    provinceList[35] = new Province(context, 36, 4, bordering(), (int)(scaleX*590+shiftX), (int)(scaleY*186+shiftY), "China", 0.5+vary());
	    borders = new ArrayList<>();
	    borders.add(0, 36); 
	    provinceList[38] = new Province(context, 39, 4, bordering(), (int)(scaleX*729+shiftX), (int)(scaleY*250+shiftY), "Philipines", 0.5+vary());
	    borders = new ArrayList<>();
	    borders.add(0, 33);     borders.add(1, 34);     borders.add(2, 35);     borders.add(3, 36);     borders.add(4, 32);     borders.add(5, 30); 
	    provinceList[32] = new Province(context, 33, 4, bordering(), (int)(scaleX*665+shiftX), (int)(scaleY*158+shiftY), "Mongolia", 0.5+vary());
	    borders = new ArrayList<>();
	    borders.add(0, 35);     borders.add(1, 34);     borders.add(2, 33); 
	    provinceList[34] = new Province(context, 35, 4, bordering(), (int)(scaleX*756+shiftX), (int)(scaleY*183+shiftY), "Japan", 0.5+vary());
	    borders = new ArrayList<>();
	    borders.add(0, 32);     borders.add(1, 33);     borders.add(2, 34);     borders.add(3, 35);     borders.add(4, 1);     borders.add(5, 31); 
	    provinceList[33] = new Province(context, 34, 4, bordering(), (int)(scaleX*719+shiftX), (int)(scaleY*99+shiftY), "Kamchatka", 0.6+vary());
	    borders = new ArrayList<>();
	    borders.add(0, 31);     borders.add(1, 32);     borders.add(2, 34);     borders.add(3, 30); 
	    provinceList[30] = new Province(context, 31, 4, bordering(), (int)(scaleX*667+shiftX), (int)(scaleY*95+shiftY), "Yakutsk", 0.5+vary());
	    borders = new ArrayList<>();
	    borders.add(0, 32);     borders.add(1, 34);     borders.add(2, 33);     borders.add(3, 31);     borders.add(4, 30); 
	    provinceList[31] = new Province(context, 32, 4, bordering(), (int)(scaleX*660+shiftX), (int)(scaleY*139+shiftY), "Irkustsk", 0.5+vary());
	    borders = new ArrayList<>();
	    borders.add(0, 30);     borders.add(1, 36);     borders.add(2, 31);     borders.add(3, 32);     borders.add(4, 33);     borders.add(5, 29); 
	    provinceList[29] = new Province(context, 30, 4, bordering(), (int)(scaleX*590+shiftX), (int)(scaleY*71+shiftY), "Siberia", 0.5+vary());
	    borders = new ArrayList<>();
	    borders.add(0, 40);     borders.add(1, 38);     borders.add(2, 36);     borders.add(3, 37); 
	    provinceList[37] = new Province(context, 38, 4, bordering(), (int)(scaleX*644+shiftX), (int)(scaleY*239+shiftY), "Siam", 0.7+vary());
	    borders = new ArrayList<>();
	    borders.add(0, 37);     borders.add(1, 38);     borders.add(2, 28);     borders.add(3, 36);     borders.add(4, 27); 
	    provinceList[36] = new Province(context, 37, 4, bordering(), (int)(scaleX*558+shiftX), (int)(scaleY*218+shiftY), "India", 0.5+vary());
	    borders = new ArrayList<>();
	    continents[4].fill(26, 38);
	    color = Color.argb(255, 242, 126, 188);

        continents[5] = new Continent(5, color, "Australia", 2, 0.8+vary());
	    borders.add(0, 41);     borders.add(1, 43);     borders.add(2, 42);     borders.add(3, 38); 
	    provinceList[39] = new Province(context, 40, 5, bordering(), (int)(scaleX*645+shiftX), (int)(scaleY*290+shiftY), "Indonesia", 0.8+vary());
	    borders = new ArrayList<>();
	    borders.add(0, 41);     borders.add(1, 43); 
	    provinceList[40] = new Province(context, 41, 5, bordering(), (int)(scaleX*745+shiftX), (int)(scaleY*301+shiftY), "New Guinea", 0.5+vary());
	    borders = new ArrayList<>();
	    borders.add(0, 42);     borders.add(1, 43);     borders.add(2, 41);     borders.add(3, 40);     borders.add(4, 44); 
	    provinceList[42] = new Province(context, 43, 5, bordering(), (int)(scaleX*702+shiftX), (int)(scaleY*328+shiftY), "Eastern Australia", 0.5+vary());
	    borders = new ArrayList<>();
	    borders.add(0, 43);     borders.add(1, 40); 
	    provinceList[41] = new Province(context, 42, 5, bordering(), (int)(scaleX*658+shiftX), (int)(scaleY*336+shiftY), "Western Australia", 0.5+vary());
	    borders = new ArrayList<>();
	    borders.add(0, 43); 
	    provinceList[43] = new Province(context, 44, 5, bordering(), (int)(scaleX*782+shiftX), (int)(scaleY*344+shiftY), "New Zealand", 0.5+vary());
	    borders = new ArrayList<>();
	    continents[5].fill(39, 43);
    }
}